services:
    maths-webserver:
        image: httpd:alpine
        restart: on-failure
        volumes:
            - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
            - ./config/tls/webserver:/usr/local/apache2/conf/
        networks:
            tier1-network:
            tier2-network:
        ports:
            - 443:443

    maths-webapp:
        image: maths-webapp:latest
        restart: on-failure
        volumes:
            - ./config/config.json:/config/config.json
            - ./config/tls/webapp/server.pem:/tls/server.pem:ro
            - ./config/tls/database/cacerts.pem:/tls/database.pem:ro
        networks:
            tier2-network:
            tier3-network:
        ports:
            - 8043:8043

    maths-database:
        image: maths-database:latest
        restart: on-failure
        volumes:
            - ./database/data:/var/lib/mysql
            - ./config/maths.cnf:/etc/mysql/conf.d/maths.cnf:ro
            - ./config/tls/database/server.key:/etc/mysql/tls/server.key:ro
            - ./config/tls/database/server.crt:/etc/mysql/tls/server.crt:ro
        networks:
            tier3-network:

networks:
    tier1-network:
        ipam:
            config:
                - subnet: 10.0.1.0/24

    tier2-network:
        ipam:
            config:
                - subnet: 10.0.2.0/24

    tier3-network:
        ipam:
            config:
                - subnet: 10.0.3.0/24
            